### PR TITLE
Fix extracting line feeds from files with CRLF

### LINKED ISSUE #135: Clusters eat one character of line endings with two characters
**Describe the bug**

In files with `\r\n` as line endings, the last character of the ending '\n' is eaten on constructing the documentation.

I encountered this bug when I tried to debug #124.

**To Reproduce**

Steps to reproduce the behaviour:

1. A file containing `\r\n` as line feeds
2. Run `cargo spellcheck reflow` on that file
3. Results are off and line feeds have changed

**Expected behavior**

A proper reflow.

**Please complete the following information:**
 - System: 
 - Obtained: git
 - Version:  `v0.5.1-alpha.0`

**Additional context**

### PR DESCRIPTION
**Pull request by KuabeM**
## What does this PR accomplish?

 * 🩹 Bug Fix

Reflow on files with CRLF line endings did not work properly. It appeared that line endings with two characters like `\r\n` dropped the last character somewhere in the process of building the `CheckableChunks`.

Closes #135

## Changes proposed by this PR:

When a `TrimmedLiteral` is extracted we more or less assume that the line ending has only one character.

The proposed solution seems a bit like a hack since we check the length of the line ending and extend the respective span by one. However,  I could not think of a better solution without changing everything.

## Notes to reviewer:

If the solution will be accepted, I'd suggest extracting the `extrac_delimiter()` function into utils.

## 📜 Checklist

 * [x] Works on the `./demo` sub directory
 * [x] Test coverage is excellent and passes
 * [x] Documentation is thorough

### CODE REVIEW

File: src/reflow/tests.rs [hunk 1]
```diff
@@ -719,3 +719,13 @@ of `0`.
 "###
     );
 }
+
+#[test]
+fn reflow_crlf() {
+    const INPUT: &'static str = "        /// cargo spellcheck can be configured with `-m <code>` to return a non-zero return code.\r\n        struct Foo {}";
+    println!("{}", INPUT);
```
Comment (drahnr) [inline src/reflow/tests.rs:726]:
```suggestion
    println!("{:?}", INPUT);
```

File: src/documentation/literal.rs [hunk 2]
```diff
@@ -162,6 +162,18 @@ impl TryFrom<(&str, proc_macro2::Literal)> for TrimmedLiteral {
         // Either cut off `]` or `\n` - we don't need either.
         span.end.column = span.end.column.saturating_sub(1);
 
+        // If the line ending has more than one character, we have to account
+        // for that. Otherwise cut of the last character of the ending such that
+        // we can't properly detect them anymore.
+        if crate::reflow::extract_delimiter(content)
```
Comment (drahnr) [inline src/documentation/literal.rs:168]: we should consider detecting the delimiter from `rendered` (extracted blow) and fallback on the entire `content` as stage 2 and stage 3 use the default `\n`. This is mostly a perf thing avoiding to traverse the full content multiple times and as a fix for files that has multiple different line endings.

**Review by drahnr — CHANGES_REQUESTED** [review]
Really small changes, looks good overall!

File: src/documentation/literal.rs (hunk 2 above)
Comment (KuabeM) [reply src/documentation/literal.rs:168]: That was my first attempts but the last character is dropped in the extraction of `rendered`. Unfortunately, we have to traverse content here.

File: src/reflow/tests.rs (hunk 1 above)
Comment (KuabeM) [reply src/reflow/tests.rs:726]: I deliberately used the default formatter to check if the actual string contains the indentation as I wanted it to be.

File: src/documentation/literal.rs (hunk 2 above)
Comment (drahnr) [reply src/documentation/literal.rs:168]: I guess technically we could convert the `Span` to a `Range` which we can extend easily by 2 characters and compare the last two to all known line endings or comment closing characters to determine the type. But that won't give us any performance edge since the conversion currently traverses the whole `content` again, without any caching done. Maybe adding a `Option<HashMap<..>` would be viable and introducing `Content` type which implements `Deref<str>`. But that's a separate topic.
I also did not take into account comments which do not contain a linewrap, so that would always fail.

Mea culpa, good as is :+1:

File: src/reflow/tests.rs (hunk 1 above)
Comment (drahnr) [reply src/reflow/tests.rs:726]: My idea was to get escaped newlines printed, so one actually sees which newline variant fails, but either way is fine.

Comment (KuabeM) [reply src/reflow/tests.rs]: Also true, makes more sense :+1:

**Review by drahnr — APPROVED** [review]
:checkered_flag: :racing_car:
