### PR TITLE
fix/emojis-and-vulgar-fractions: hunspell should not check it

### LINKED ISSUE #141: vulgar fractions and single emojis are detected as mistakes
**Describe the bug**

`⅔` is marked as error.

**To Reproduce**

Steps to reproduce the behaviour:

1. A file containing `⅔`
2. Run `cargo-spellcheck $file`
3. See the thing marked as possible spelling mistake

**Expected behavior**

Accept it and be happy.

**Please complete the following information:**
 - System:  Fedora
 - Obtained:  cargo
 - Version:

### PR DESCRIPTION
**Pull request by laysauchoa**
## What does this PR accomplish?

 * 🩹 Bug Fix
 * 🦚 Feature

Closes #141 .

## 📜 Checklist

 * [x] Works on the `./demo` sub directory
 * [X] Test coverage is excellent and passes
 * [X] Documentation is thorough

## Test for emojis
error: spellcheck(Hunspell)
```
  --> /home/tmhdev/Documents/rust_samples/recursion_rust/src/fibonnacci.rs:2
   |
 2 |  😘🤗🦀
   |  ^^^
   |   Possible spelling mistake found.
```
```
error: spellcheck(Hunspell)
  --> /home/tmhdev/Documents/rust_samples/recursion_rust/src/fibonnacci.rs:2
   |
 2 |  😘🤗🦀⅔⅔
   |  ^^^^^
   |   Possible spelling mistake found.

error: spellcheck(Hunspell)
  --> /home/tmhdev/Documents/rust_samples/recursion_rust/src/fibonnacci.rs:3
   |
 3 |  ⅔⅔
   |  ^^
   |   Possible spelling mistake found.
```
I ran again and the possible mistake is not seen.

This PR refers to https://github.com/drahnr/cargo-spellcheck/issues/141

### CODE REVIEW

**Comment by laysauchoa** [comment]
Just checking if the changes will be in this part of the code. Still need to find something for fractions, maybe https://crates.io/crates/unicode-segmentation

**Comment by drahnr** [comment]
The code location is correct :+1: , it would be nice to make it a separate module, since other backends might want to allow whitlisting emojis and graphemes as well.
Note that graphemes are multiple unicode characters, so a more fully future lib might make more sense i.e. [`unic`](https://lib.rs/crates/unic)

**Comment by laysauchoa** [comment]
ok, not sure if the other unicode should also be included here besides emojis and vulgar fractions. I only focused on those two. Feel free to drop any tips about it. I could not find in unic a better way to handle with vulgar fractions, maybe I am missing something? Another possibility, would be to find if the char is in the ranges of vulgar fractions but maybe not so readable.

File: src/checker/hunspell.rs [hunk 1]
```diff
@@ -29,6 +29,33 @@ pub struct HunspellWrapper(pub Arc<Hunspell>);
...
+            return false;
+        }
+    }
+    return true;
+}
+
+// The value is `true` if given character is a vulgar fraction
+pub fn is_vulgar_fraction(character: char) -> bool {
+    let unicode_name = unicode_names2::name(character).map(|n| n.to_string());
+    let vulgar = "VULGAR FRACTION";
```
Comment (drahnr) [inline src/checker/hunspell.rs:51]: Since this is going to be a rather hot function being called very often, it should really be fast. So a string comparison is a bit hard to justify. If we can check for the character page that would be way more efficient.

File: src/checker/hunspell.rs [hunk 2]
```diff
@@ -243,6 +270,13 @@ fn obtain_suggestions<'s>(
             .filter(|x| x.len() > 1) // single char suggestions tend to be useless
             .collect::<Vec<_>>();
 
+        // strings made of vulgar fraction or emoji
+        if vulgar_fraction_or_emoji(word.clone()) {
+            trace!(target: "quirks", "Found emoji or vulgar fraction character, treating {} as ok", &word);
+            return;
```
Comment (drahnr) [inline src/checker/hunspell.rs:276]: I can imagine, that cases of type `${fraction}-yada` would be ok as well, yet `yada` should potentially be checked.

File: src/checker/hunspell.rs [hunk 3]
```diff
@@ -273,3 +307,62 @@ fn obtain_suggestions<'s>(
...
+    vulgar_fraction_four_fifths: ( '⅘', true),
+    vulgar_fraction_one_sixth: ('⅙', true),
+    vulgar_fraction_five_sixths: ('⅚', true),
+    vulgar_fraction_one_eighth: ('⅛', true),
+    vulgar_fraction_three_eighths: ('⅜', true),
+    vulgar_fraction_five_eights: ('⅝', true),
+    vulgar_fraction_five_eighths: ('⅝', true),
+    vulgar_fraction_seven_eighths: ('⅞', true),
+    vulgar_fraction_zero_thirds: ('↉', true),
+
```
Comment (drahnr) [inline src/checker/hunspell.rs:367]: This is really nice test coverage!

File: src/checker/hunspell.rs [hunk 4]
```diff
@@ -29,6 +29,33 @@ pub struct HunspellWrapper(pub Arc<Hunspell>);
 unsafe impl Send for HunspellWrapper {}
 unsafe impl Sync for HunspellWrapper {}
 
+// The value is `true` if string is made of emoji's
+// or unicode `VULGAR FRACTION`
+pub fn vulgar_fraction_or_emoji(word: String) -> bool {
+    if word.is_empty() {
+        return false;
+    }
+    for c in word.clone().chars() {
```
Comment (drahnr) [inline src/checker/hunspell.rs:38]: do we need the clone here?

File: src/checker/hunspell.rs [hunk 5]
```diff
@@ -29,6 +29,33 @@ pub struct HunspellWrapper(pub Arc<Hunspell>);
 unsafe impl Send for HunspellWrapper {}
 unsafe impl Sync for HunspellWrapper {}
 
+// The value is `true` if string is made of emoji's
+// or unicode `VULGAR FRACTION`
+pub fn vulgar_fraction_or_emoji(word: String) -> bool {
```
Comment (drahnr) [inline src/checker/hunspell.rs:34]: We should also avoid the copy here, maybe a `&str` would suffice as well?

**Review by drahnr — CHANGES_REQUESTED** [review]
There are a few performance concerns, the general approach looks really good :+1:

File: src/checker/hunspell.rs (hunk 2 above)
Comment (laysauchoa) [reply src/checker/hunspell.rs:260]: I am not sure what you mean with yada, is this a test case to be added?

File: src/checker/hunspell.rs (hunk 5 above)
Comment (laysauchoa) [reply src/checker/hunspell.rs]: you are right! I applied the changes.

File: src/checker/hunspell.rs (hunk 2 above)
Comment (drahnr) [reply src/checker/hunspell.rs:264]: `yada` is just an example of an arbitrary suffix, so we could have constructs `½-baked` or `½-past` which might or might not be acceptable, but I guess that could be handled with regular hunspell quirks as well. Now that you found the solution using regex all of this could be done via regex, but I would prefer this to be a simple `on`/`off` configuration flag, rather than having people dig through this or accept false-positives.

So given that, ignore my comment above.

File: src/checker/hunspell.rs [hunk 6]
```diff
@@ -25,12 +25,23 @@ use anyhow::{anyhow, bail, Result};
...
 
 pub struct HunspellWrapper(pub Arc<Hunspell>);
 
 unsafe impl Send for HunspellWrapper {}
 unsafe impl Sync for HunspellWrapper {}
 
+// The value is `true` if string is made of emoji's
+// or unicode `VULGAR FRACTION`
+pub fn vulgar_fraction_or_emoji(word: &str) -> bool {
+    let set = RegexSetBuilder::new(&[r"[\u00BC-\u00BE\u2150-\u215E-\u2189]", r"^[\p{Emoji}]+$"])
```
Comment (drahnr) [inline src/checker/hunspell.rs:38]: Compiling regexp is quite expensive, so this should definitely be called in a lazy static at a very very early point (not that since this might be called from a thread pool with rayon, make sure this is initialized early on in `Hunspell::check()`

File: src/checker/hunspell.rs [hunk 7]
```diff
@@ -25,12 +25,23 @@ use anyhow::{anyhow, bail, Result};
...
+        .case_insensitive(true)
+        .build()
+        .unwrap();
```
Comment (drahnr) [inline src/checker/hunspell.rs:41]: Prefer expects :)

File: src/checker/hunspell.rs [hunk 8]
```diff
@@ -247,6 +258,12 @@ fn obtain_suggestions<'s>(
             .filter(|x| x.len() > 1) // single char suggestions tend to be useless
             .collect::<Vec<_>>();
 
+        // strings made of vulgar fraction or emoji
+        if vulgar_fraction_or_emoji(&word) {
+            trace!(target: "quirks", "Found emoji or vulgar fraction character, treating {} as ok", &word);
```
Comment (drahnr) [inline src/checker/hunspell.rs:263]: :+1:

File: src/checker/hunspell.rs [hunk 9]
```diff
@@ -247,6 +258,12 @@ fn obtain_suggestions<'s>(
...
+            return;
```
Comment (drahnr) [inline src/checker/hunspell.rs:264]:
```suggestion
```

File: src/checker/hunspell.rs [hunk 10]
```diff
@@ -247,6 +258,12 @@ fn obtain_suggestions<'s>(
             .filter(|x| x.len() > 1) // single char suggestions tend to be useless
             .collect::<Vec<_>>();
 
+        // strings made of vulgar fraction or emoji
+        if vulgar_fraction_or_emoji(&word) {
```
Comment (drahnr) [inline src/checker/hunspell.rs:262]: I think it's best to make this configurable, but make it default to on.

**Review by drahnr — DISMISSED** [review]
Small set of changes, but other than that good to go, I took the liberty to fix the botched merge commit.

**Comment by laysauchoa** [comment]
Hi @drahnr, thanks for fixing the test back to working :pray: . So if regex is a too expensive operation, and also convert to the name as it was done before, then another option would be have the VULGAR FRACTIONS* hard-coded and then simple check if a char is on that list and use unic emoji for check of the emoji. What do you think? Which approach you propose and do you mean to add a flag to enable the check of chars and emoji?

**Comment by drahnr** [comment]
The expensive part is the refer compilation, not applying the compiled regexp :) so if you wrap that in a lazy static it should be fine.

If you have a better/faster idea, go for it. If unsure, measure with i.e. a criterion bench or a simple cputime crate.

**Comment by drahnr** [comment]
I tend to prefer unic since the general plan would be to move in that direction anyways

**Comment by drahnr** [comment]
Ping :upside_down_face:

**Comment by drahnr** [comment]
@laysauchoa finally got around to taking another look at this, and I'd say this is good to go as is now :)

File: src/config/hunspell.rs [hunk 11]
```diff
@@ -7,6 +7,10 @@ use anyhow::{bail, Result};
 
 use serde::{Deserialize, Serialize};
 
+const fn yes() -> bool {
```
Comment (laysauchoa) [inline src/config/hunspell.rs:10]: is this used some place else? I can't find it

File: src/checker/hunspell.rs [hunk 12]
```diff
@@ -98,6 +99,21 @@ fn cache_builtin() -> Result<(PathBuf, PathBuf)> {
     Ok((path_dic, path_aff))
 }
 
+/// The value is `true` if string is made of emoji's
+/// or unicode `VULGAR FRACTION`.
+pub fn consists_of_vulgar_fractions_or_emojis(word: &str) -> bool {
+    lazy_static! {
+        static ref VULAGAR_OR_EMOJI: regex::RegexSet = regex::RegexSetBuilder::new(&[
```
Comment (laysauchoa) [inline src/checker/hunspell.rs:106]: VULGAR_OR_EMOJI?

Comment (drahnr) [reply src/checker/hunspell.rs:106]: Hmm, I thought I fixed that already :monocle_face: :coffee:

**Comment by drahnr** [comment]
The CI issue is unrelated to these changes, it's just the first time it popped up - filed https://github.com/bminixhofer/nlprule/issues/68 but is most likely a `lazycell` issue.
