### PR TITLE
fix: remove suggestions' duplication

### LINKED ISSUE #10: merge exact matches of overlapping suggestion
`languagetool` includes `hunspell` on the backend, now both checkers provide a suggestion for the same item, which is pointless to the user and when fixing interactively, this will cause broken messages for i.e. tokens which are replaced by tokens of different length

### PR DESCRIPTION
**Pull request by granddaifuku**
## What does this PR accomplish?

 * 🩹 Bug Fix

Closes #10 .

## Changes proposed by this PR:

To remove the duplicated suggestions, the `Vector of Suggestion` is converted once to a `HashSet` and then again to a `Vector`.

## Notes to reviewer:

This PR tries to resolve the 🔰 part of the issue, but I'm willing to work on further parts of it.

## 📜 Checklist

 * [x] Works on the `./demo` sub directory
 * [ ] Test coverage is excellent and passes
 * [x] Documentation is thorough

### CODE REVIEW

File: src/checker/mod.rs [hunk 1]
```diff
@@ -110,9 +112,12 @@ impl Checker for Checkers {
             collective.extend(nlprule.check(origin, chunks)?);
         }
 
-        collective.sort();
+        // Convert into a set to remove the duplicated suggestions
+        let set: HashSet<Suggestion> = HashSet::from_iter(collective.iter().cloned());
+        let mut suggestions: Vec<Suggestion<'s>> = Vec::from_iter(set);
+        suggestions.sort();
```
Comment (drahnr) [inline src/checker/mod.rs:118]: Couldn't we integrate this by just making `collective` a hashset, which would avoid one extra iteration?

Comment (drahnr) [reply src/checker/mod.rs:118]: Note that the `HashSet` only would cover the exact overlaps, but not i.e. multiple mistakes that are overlapping.

**Comment by drahnr** [comment]
This practically solves the problem of identical suggestions, but how about partial overlaps? Do you have an idea (theoretically) how to deal with multiple overlapping suggestions, at least avoiding corruption?

File: src/checker/mod.rs (hunk 1 above)
Comment (granddaifuku) [reply src/checker/mod.rs:116]: Thank you for your reviews!

1. I updated the branch so that reduces one iteration by making `collective` a HashSet.

2. I'm striving to find a better solution for the case there are multiple mistakes.

    Could I make sure my understanding is that
    > multiple mistakes that are overlapping and/or with different fix suggestions.

    means `Where checkers point out are same, but the way they suggest is different`?
    
    If so, I think we could achieve this by iterating through both resulted collections and merging the overlapped ones based on the fields of `Suggestion`: `origin`, `span`, and `range`. (Here, in this case, we don't need to use HashSet.)
    I'll appreciate it if you could give me feedback on this!

**Comment by granddaifuku** [comment]
Thank you for your reviews!

I'm still striving to find a better solution for the case there are multiple mistakes.

Could I make sure my understanding is that
> multiple mistakes that are overlapping and/or with different fix suggestions.

means `Where checkers point out are same, but the way they suggest is different`?

If so, I think we could achieve this by iterating through both resulted collections and merging the overlapped ones based on the fields of Suggestion: origin, span, and range. (Here, in this case, we don't need to use HashSet.)
I'll appreciate it if you could give me feedback on this!

**Comment by drahnr** [comment]
The difficulty is overlapping changes that are confliciting, or even if they're not, how to merge them.

My idea would be, to omit one of them (the latter one), and re-run on the relevant chunk _after_ applying the first suggestion.

**Comment by drahnr** [comment]
Yes, that's precisely it. Sorting might help and then iterating over adjacent tuples, just an idea. I don't have a vision on how the checker would be re-run, though. In a perfect world, without any additional IO.

**Comment by granddaifuku** [comment]
Great thanks!

Maybe it will take a few days, but I will give it a try.

**Comment by granddaifuku** [comment]
Sorry for the slow progress.
I have just implemented a method to determine the overlappings. After this, I will implement the method to determine and process the checker's overlappings.

**Comment by drahnr** [comment]
Hey @granddaifuku 👋 - gentle ping in the new year 🎆 - is there anything you're blocked on I could help with?

**Comment by granddaifuku** [comment]
Happy new year @drahnr!  Thank you for caring about this!!

I'm sorry I couldn't make any progress on this PR due to my thesis.
My thesis defense is at the beginning of February, so I can restart working on this around the mid of February.

**Comment by drahnr** [comment]
Best of luck (which I am sure you don't need) @granddaifuku ! Feel free to ping me once you're done :)

**Comment by drahnr** [comment]
Gentle ping, now that people are starting to hit issues with this i.e. #295

**Comment by granddaifuku** [comment]
@drahnr 
Thank you for reaching out to me multiple times.  
I would like you to know that my thesis defense is now over, so I will restart working on this PR this Sunday!

**Comment by granddaifuku** [comment]
@drahnr 
I made some updates that detect overlapped suggestions.
However, I still could not find a way to re-run the checker after internally applying the first suggestion.
Could you help me with that point?

**Comment by drahnr** [comment]
Hey @granddaifuku I'll try to find some time later this week :)

File: src/checker/mod.rs [hunk 2]
```diff
@@ -102,17 +104,36 @@ impl Checker for Checkers {
...
+        let mut i: usize = 0;
+        while i < suggestions.len() - 1 as usize {
+            let cur = suggestions[i].clone();
+            i += 1;
+
+            while cur.is_overlapped(&suggestions[i]) {
+                let omit = suggestions.remove(i);
+                omitted.push(omit.chunk.clone());
+            }
+        }
```
Comment (drahnr) [inline src/checker/mod.rs:132]: I'd recommend to use `suggestions.iter().filter_map(..)` in conjuction with a collection of overlapping ones.

File: src/suggestion.rs [hunk 3]
```diff
@@ -315,6 +315,24 @@ pub struct Suggestion<'s> {
...
 
+impl<'s> Suggestion<'s> {
+    /// Determine if there is overlap.
+    pub fn is_overlapped(&self, other: &Self) -> bool {
+        if self.origin != other.origin {
+            return false;
+        }
+        if self.span.start.line != other.span.start.line {
+            return false;
+        }
```
Comment (drahnr) [inline src/suggestion.rs:326]: The first line being equal is not necessarily a good indicator, right now this _might_ work, but the plan is to have multiline corrections eventually.

**Review by drahnr — CHANGES_REQUESTED** [review]
Good start :) a few stylicstic and domain specific topics to address, regarding the re-running of the checker, it's a non-trivial undertaking and should possibly be deferred to separate PR.

File: src/checker/mod.rs [hunk 4]
```diff
@@ -102,17 +104,34 @@ impl Checker for Checkers {
...
+            .iter()
+            .enumerate()
+            .filter_map(|(idx, cur)| {
+                if idx > 0 && cur.is_overlapped(&suggestions[idx - 1]) {
+                    Some(cur.chunk.clone())
+                } else {
+                    None
+                }
+            })
+            .collect::<Vec<_>>();
```
Comment (drahnr) [inline src/checker/mod.rs:132]: This doesn't work like you expect :)

`.iter()` takes a immutable reference and hence cannot modify `suggestions`.

```suggestion
        let suggestions = Vec::from_iter(suggestions
            .into_iter()
            .enumerate()
            .filter_map(|(idx, cur)| {
                if idx == 0 || !cur.is_overlapped(&suggestions[idx - 1]) {
                    Some(cur.chunk)
                } else {
                    None
                }
            }));
```

**Review by drahnr — CHANGES_REQUESTED** [review]
Generally looks good, one fix pending :)

**Comment by granddaifuku** [comment]
@drahnr 
Great, thank you for your review! I have made a change to remove any overlapping suggestions from the suggestions vector. I will also be making a change to the logic to be more accurate in detecting overlap and will update you once that is done.

**Comment by granddaifuku** [comment]
@drahnr 
I wanted to let you know that I made some changes to the is_overlapped method to check for overlaps in multi-line suggestions. Whenever you have some free time, I'd appreciate it if you could take a look and review the changes I made. If everything seems to be in order, I would like to add tests for the updated functionality.

File: src/suggestion.rs [hunk 5]
```diff
@@ -315,6 +315,26 @@ pub struct Suggestion<'s> {
...
+        if self.origin != other.origin {
+            return false;
+        }
+
+        if self.span.end.line < other.span.start.line || other.span.end.line < self.span.start.line
+        {
+            return false;
+        }
+
+        if self < other {
```
Comment (drahnr) [inline src/suggestion.rs:330]:
```suggestion
        if self < other {
```

I don't quite understand this one? The implementation of `Ord` is rather complicated, so I'd prefer to be explicit here.

Comment (granddaifuku) [reply src/suggestion.rs]: @drahnr 
I wanted to inform you that I have made a change to explicitly compare the spans, rather than relying on the Ord implementation. I would greatly appreciate it if you could take a moment to review these changes. If everything looks good, I will proceed to update the test cases accordingly.

**Comment by drahnr** [comment]
@granddaifuku sorry for the long silence, is there anything left to do from your perspective? Did you test it as part of the dummy projects in the working tree?

**Comment by granddaifuku** [comment]
@drahnr 
Thank your response, and I'm sorry for not ping you for a long time.
I already checked it with a demo project, and it worked.
I will make this PR ready for a review then.

**Review by drahnr — APPROVED** [review]
